### ISSUE TITLE
Broken Link for AWS Cloudformation Deployment 

### ISSUE THREAD

**Issue by kaizio** [civiform/docs#106]
PR #82 introduced a broken link for AWS Cloudformation deployment for [docs/it-manual/sre-playbook/initial-deployment.md](/civiform/docs/tree/main/docs/it-manual/sre-playbook/initial-deployment.md) on line 7. 

https://github.com/civiform/civiform-deploy does not contain an infra folder as https://github.com/seattle-civiform/civiform-deploy does.

**Comment by bion** [comment]
Thanks!
