### ISSUE TITLE
Support Dark Modes

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/docs#5]
It would be nice if there could be a toggle for light/dark mode or base it on what the user has selected as default in their Operating System.

**Comment by rasmi** [comment]
This feature has been [enabled in our GitBook environment](https://changelog.gitbook.com/may-2023/30-may-a-light-dark-mode-toggle-and-new-customization-options), you may need to refresh your docs page to see. It is set to the system preference by default but can be toggled at the bottom of the page. Thanks @gwendolyngoetz @dkatzz!

**Comment by gwendolyngoetz** [comment]
Thank you @rasmi !!!!!!!
